openapi: 3.0.0
info:
  title: 'Everform API Documentation'
  description: 'Everform API Documentation'
  contact:
    email: nqhung291@gmail.com
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000/api/'
    description: 'Everform API Server'
paths:
  /login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login
      operationId: d618a255475240ba3d40cc39692cd924
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
              type: object
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                type: object
              example:
                success: true
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                type: object
              example:
                success: false
